site_name: Bare Minimum Docs  
site_url: https://bareminimumstudios.github.io/Bare-Minimum-Docs/
site_description: 'Bare Minimum Wiki'

theme:  
  name: null  
  custom_dir: mkdocs-material/material

  features:  
    - search.suggest  
    - search.highlight  
    - search.share   
    - navigation.indexes  
    - navigation.expand  
    - navigation.top  
    - navigation.tracking  
    - navigation.tabs  
    - navigation.sections  
    - header.autohide  
    - navigation.footer  
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - content.tooltips

  palette: 
    - scheme: slate  
      primary: indigo  
      accent: blue  
      toggle:  
        icon: material/brightness-4  
        name: Switch to light mode 

    - scheme: default  
      primary: indigo  
      accent: blue  
      toggle:  
        icon: material/brightness-7  
        name: Switch to dark mode  

  favicon: assets/favicon.png  # Path to the favicon
  icon:
    logo: octicons/accessibility-16  # Logo icon
  language: en  # Language setting for the website
  font:  # Font settings
    text: Fira Sans  # Font for regular text
    code: Fira Mono  # Font for code blocks

copyright: "Documentation by <a style=\"color: #13A6F0;\" href=\"https://github.com/pokesmells\">Poke</a>, with assistance from the Bare Minimum Team."
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/pcRw79hwey
    - icon: fontawesome/brands/github
      link: https://github.com/BareMinimumStudios
  analytics:
      provider: google
      property: G-KT6JJKSEP1 
  consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeat visits and preferences, and to measure the effectiveness of our documentation and how well users find what they need. By consenting, you help us improve our documentation.  
  projects:
      docs:
          repo: https://github.com/BareMinimumStudios/Bare-Minimum-Docs
          name: Bare Minimum Docs
      playerex:
          repo: https://github.com/BareMinimumStudios/playerex
          name: PlayerEx
      data-attributes:
          repo: https://github.com/BareMinimumStudios/data-attributes
          name: Data Attributes
      opc:
         repo: https://github.com/BareMinimumStudios/Offline-Player-Cache
         name: Offline Player Cache       

markdown_extensions:  # Markdown extensions/settings
    - admonition  # Allow admonitions in Markdown
    - attr_list  # Allow attribute lists in Markdown
    - md_in_html
    - pymdownx.betterem
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tasklist:  # Enable task lists in Markdown
        custom_checkbox: true  # Custom checkbox style
    - pymdownx.details  # Enable details/summary in Markdown
    - pymdownx.keys  # Enable keyboard shortcuts in Markdown
    - pymdownx.arithmatex:  # Enable math rendering in Markdown
        generic: true  # Use generic LaTeX mode
    - pymdownx.highlight:  # Enable syntax highlighting in Markdown
        anchor_linenums: true  # Add anchor links to line numbers
        line_spans: --span
        pygments_lang_class: true
    - pymdownx.inlinehilite  # Enable inline code highlighting
    - pymdownx.snippets  # Enable code snippets in Markdown
    - footnotes  # Enable footnotes in Markdown
    - pymdownx.superfences:  # Enable custom fenced code blocks in Markdown
        custom_fences:  # Define custom fences
          - name: mermaid  # Name of custom fence
            class: mermaid  # CSS class for custom fence
            format: !!python/name:pymdownx.superfences.fence_code_format  # Format for custom fence
    - pymdownx.tabbed:  # Enable tabbed sections in Markdown
        alternate_style: true  # Use alternate style for tabs
    - toc:  # Enable table of contents in Markdown
        permalink: true  # Add permalinks to TOC
    - pymdownx.emoji:  # Enable emoji support in Markdown
        emoji_index: !!python/name:materialx.emoji.twemoji  # Emoji index
        emoji_generator: !!python/name:materialx.emoji.to_svg  # Emoji generator
    - pymdownx.tilde  # Enable strike-through syntax using ~~~
    - pymdownx.critic  # Enable Critic Markup syntax in Markdown

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      type: timeago 
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: true

nav:
   - Home:
       - index.md
       - fabric-events.md
   - Data Attributes:
       - data-attributes/home.md
       - data-attributes/datapack-setup.md
       - data-attributes/stacking-behavior.md
       - data-attributes/overrides.md
       - data-attributes/entity-types.md
       - data-attributes/attribute-functions.md
       - data-attributes/attribute-properties.md
       - data-attributes/api.md
   - PlayerEx:
       - playerex/home.md
       - playerex/faq.md
       - playerex/in-game-content.md
       - playerex/textplaceholderapi.md
       - playerex/api.md
   - Offline Player Cache:
       - opc/home.md
       - opc/cacheablevalue.md
       - opc/api.md